"Canonical version at https://github.com/mattrco/config

"Line numbering
set number

"Search as query is typed
set incsearch

"Write buffers as needed
set autowrite

"Highlight search matches
set hlsearch

"Tab size & auto indent
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

"Show matching parens
set showmatch

"Turn off swapfiles
set noswapfile

"Don't ask to save when switching buffers
set hidden
set confirm

"Switch buffers with C-j and C-k
map <C-j> :bn <cr>
map <C-k> :bp <cr>

"Jump to the last position when reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

"Fold code based on indentation
set foldmethod=indent
set foldnestmax=2

"Map space to open/close folds
nnoremap <space> za

"Fold level for opened files
set foldlevelstart=2
"
"Vundle config
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

"Let Vundle manage Vundle
Bundle 'gmarik/vundle'

"Buffer nav
Bundle 'minibufexpl.vim'
"tagbar
Bundle 'majutsushi/tagbar'

"Go vim plugin
Bundle 'mattcottingham/vim-golang'

"Go tagbar config
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

"Toggle tagbar with F8
nmap <F8> :TagbarToggle<CR>

"Force reload of filetype plugin (for Go filetype)
filetype off
filetype plugin indent off
set runtimepath+=.vim/bundle/vim-golang/misc/vim/
filetype plugin indent on
syntax on

" go fmt on save
autocmd FileType go autocmd BufWritePre <buffer> Fmt

