export HISTSIZE=10000
export HISTCONTROL=ignoreboth

alias govuk_staging='sudo /Users/alexmuller/govuk/private-utils/script/govuk_select_organisation staging'
alias govuk_production='sudo /Users/alexmuller/govuk/private-utils/script/govuk_select_organisation production'

RESET="$(tput sgr0)"
BOLDGREEN="$(tput bold; tput setaf 2)"

PS1="\[$BOLDGREEN\][HOST]\[$RESET\] \w\$(__git_ps1) $ "

[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
  . $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
fi
