#!/bin/bash

for dir in /Users/alexmuller/govuk/*/.git
  do
    if [[ ! -e $dir/hooks/pre-commit ]]
      then
        cat > "$dir/hooks/pre-commit" <<"MYHOOK"
#!/usr/bin/env ruby

# Testing the diff that's about to be committed for secrets

full_diff = `git diff --cached --`.encode("UTF-8")

added_code = full_diff.split("\n").select { |line| line.start_with?("+") }.join("\n")

if added_code.match(/PRIVATE KEY/)
  puts "It looks like there's a private key in the code that's about to be committed. Aborting."
  exit 1
end
MYHOOK
    fi
    if [[ ! -x $dir/hooks/pre-commit ]]
      then
        chmod a+x "$dir/hooks/pre-commit"
    fi
done

