class teams::core {
  # Apps
  include projects::asset-manager
  include projects::bouncer
  include projects::business-support-api
  include projects::business-support-finder
  include projects::calculators
  include projects::calendars
  include projects::collections
  include projects::collections-api
  include projects::collections-publisher
  include projects::contacts-admin
  include projects::contacts-frontend
  include projects::content-register
  include projects::content-store
  include projects::courts-api
  include projects::courts-frontend
  include projects::design-principles
  include projects::email-alert-api
  include projects::email-alert-service
  include projects::external-link-tracker
  include projects::feedback
  include projects::finder-frontend
  include projects::frontend
  include projects::govuk_content_api
  include projects::govuk_need_api
  include projects::hmrc-manuals-api
  include projects::imminence
  include projects::info-frontend
  include projects::licence-finder
  include projects::manuals-frontend
  include projects::maslow
  include projects::metadata-api
  include projects::panopticon
  include projects::publisher
  include projects::recommended-links
  include projects::release
  include projects::router-api
  include projects::rummager
  include projects::search-admin
  include projects::short-url-manager
  include projects::side-by-side-browser
  include projects::sidekiq-monitoring
  include projects::signonotron2
  include projects::smart-answers
  include projects::specialist-frontend
  include projects::specialist-publisher
  include projects::static
  include projects::support
  include projects::support-api
  include projects::transition
  include projects::transition-config
  include projects::travel-advice-publisher
  include projects::url-arbiter
  include projects::whitehall

  # Gems
  include projects::gds-api-adapters
  include projects::gds-sso
  include projects::govspeak
  include projects::govuk_admin_template
}
