# -*- mode: sh -*-

[[ -f /opt/boxen/env.sh ]] && source /opt/boxen/env.sh

[[ -f $(brew --prefix)/etc/bash_completion ]] && . $(brew --prefix)/etc/bash_completion
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/govuk
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion
export PATH=/usr/local/go/bin:$PATH
source /opt/boxen/homebrew/bin/virtualenvwrapper.sh

### Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### java 1.8
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home

## copied from https://github.gds/gds/ida-hub/wiki/Useful-bash-aliases
workspaceDirectory=$HOME/govuk
alias dcs="cd ${workspaceDirectory}/doc-checking"
alias log="cd ${workspaceDirectory}/dropwizard-logstash"
alias box="cd ${workspaceDirectory}/ida-boxes"
alias fabr="cd ${workspaceDirectory}/ida-fabric"
alias fro="cd ${workspaceDirectory}/ida-frontend"
alias gra="cd ${workspaceDirectory}/ida-gradle"
alias hub="cd ${workspaceDirectory}/ida-hub"
alias acc="cd ${workspaceDirectory}/ida-hub-acceptance-tests"
alias con="cd ${workspaceDirectory}/ida-hub-federation-config"
alias sup="cd ${workspaceDirectory}/ida-hub-support"
alias msa="cd ${workspaceDirectory}/ida-msa"
alias srp="cd ${workspaceDirectory}/ida-sample-rp"
alias idp="cd ${workspaceDirectory}/ida-stub-idp"
alias util="cd ${workspaceDirectory}/ida-utils"
alias web="cd ${workspaceDirectory}/ida-webops"
alias sam="cd ${workspaceDirectory}/saml-lib"
alias tok="cd ${workspaceDirectory}/token-service"

# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/GHC.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

export PS1='\h:\W$(__git_ps1) \u\$ '

# use gpg-agent settings
. $HOME/.gpg-agent-info

# Load the custom .*-pass I have

for i in ~/.*-pass; do
    [ -e $i/.load.bash ] && . $i/.load.bash
done

# add nix to PATH
export PATH="$HOME/.nix-profile/bin:$PATH"

